title = "The Update Framework"
disableKinds = ["taxonomy", "taxonomyTerm"]
copyright = "The Update Framework authors"

[params]
font_awesome_version = "5.12.0"
description = "A framework for securing software update systems"
favicon = "favicon.png"

[params.logos]
navbar = "tuf-horizontal-white.png"
hero = "tuf-stacked-color.png"
cncf = "cncf-color.png"

[[params.fonts]]
name = "Alata"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Roboto Mono"
sizes = [300, 400, 600, 700]
type = "monospace"

[[menu.main]]
name = "About"
identifier = "about"
weight = 1

[[menu.main]]
name = "Overview"
parent = "about"
url = "/overview"

