[build]
publish = "public"
command = "make production-build"

[build.environment]
HUGO_VERSION = "0.60.0"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"

[[redirects]]
from = "/specification/latest"
to = "https://theupdateframework.github.io/specification/latest/"

[[redirects]]
from = "/specification/list"
to = "https://theupdateframework.github.io/specification/"

[[redirects]]
from = "/specification"
to = "https://theupdateframework.github.io/specification/latest/"
